PL/Controllers/DepartmentController.cs
using AutoMapper;
using BLL.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IMapper mapper;
        private readonly IUnitOfWork unitOfWork;


        public DepartmentController(IMapper mapper,IUnitOfWork unitOfWork)
        {
            this.mapper = mapper;
            this.unitOfWork = unitOfWork;
        }

        #region Index
        public async Task<IActionResult> Index()
        {
            var departments = await unitOfWork.DepartmentRepository.GetAll();
            var mappedDepartments= mapper.Map<IEnumerable<DepartmentViewModel>>(departments);
            return View(mappedDepartments);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DepartmentViewModel departmentViewModel)
        {
            if (ModelState.IsValid)
            {
                var mappedDepartment = mapper.Map<Department>(departmentViewModel);
                await unitOfWork.DepartmentRepository.Add(mappedDepartment);
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var department = await unitOfWork.DepartmentRepository.Get(id);

            if (department == null)
                return NotFound();

            var mappedDepartment=mapper.Map<DepartmentViewModel> (department);

            return View(mappedDepartment);
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();

            var department = await unitOfWork.DepartmentRepository.Get(id);

            if (department == null)
                return NotFound();

            var mappedDepartment = mapper.Map<DepartmentViewModel>(department);


            return View(mappedDepartment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(DepartmentViewModel departmentViewModel)
        {
            if (ModelState.IsValid)
            {
                var mappedDepartment = mapper.Map<Department>(departmentViewModel);
                await unitOfWork.DepartmentRepository.Update(mappedDepartment);
                return RedirectToAction("Index");
            }
            return View(departmentViewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var department = await unitOfWork.DepartmentRepository.Get(id);
            if (department == null)
                return NotFound();

            await unitOfWork.DepartmentRepository.Delete(department);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

PL/Controllers/EmployeeController.cs
using AutoMapper;
using BLL.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using PL.Helpers;
using PL.Models;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public EmployeeController(IUnitOfWork unitOfWork,IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }
        #region Index
        public async Task<IActionResult> Index(string SearchValue = "")
        {
            IEnumerable<Employee> employees;
            if (string.IsNullOrEmpty(SearchValue))
            {
                employees = await unitOfWork.EmployeeRepository.GetAll();
            }
            else
            {
                employees = await unitOfWork.EmployeeRepository.Search(SearchValue);
            }
            var mappedEmployee = mapper.Map<IEnumerable<EmployeeViewModel>>(employees);

            return View(mappedEmployee);
        }
        #endregion

        #region Create
        public async Task<IActionResult> Create()
        {
            var departments = await unitOfWork.DepartmentRepository.GetAll();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                employeeViewModel.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Images");
                var mappedEmployee = mapper.Map<Employee>(employeeViewModel);
                await unitOfWork.EmployeeRepository.Add(mappedEmployee);
                return RedirectToAction("Index");
            }
            return View(employeeViewModel);
        }
        #endregion

        #region Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var employee = await unitOfWork.EmployeeRepository.Get(id);
            var dapartmentName = await unitOfWork.EmployeeRepository.GetDepartmentByEmployee(id);
            var mappedEmployee = mapper.Map<EmployeeViewModel>(employee);


            if (employee == null)
                return NotFound();

            return View(mappedEmployee);
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();

            var employee = await unitOfWork.EmployeeRepository.Get(id);

            var mappedEmployee = mapper.Map<EmployeeViewModel>(employee);

            if (employee == null)
                return NotFound();

            return View(mappedEmployee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(EmployeeViewModel employeeViewModel)
        {

            if (ModelState.IsValid)
            {
                employeeViewModel.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Images");

                var mappedEmployee = mapper.Map<Employee>(employeeViewModel);

                await unitOfWork.EmployeeRepository.Update(mappedEmployee);
                return RedirectToAction("Index");
            }
            return View(employeeViewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var employee = await unitOfWork.EmployeeRepository.Get(id);
            if (employee == null)
                return NotFound();
            DocumentSettings.DeleteFile("Images", employee.ImageUrl);
            await unitOfWork.EmployeeRepository.Delete(employee);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

PL/Controllers/RolesController.cs
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace PL.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public RolesController(RoleManager<IdentityRole> roleManager,UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        #region Index
        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }
        #endregion

        #region Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityRole identityRole)
        {
            if (ModelState.IsValid)
            {
                var result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }
            return View("Index");
        }
        #endregion

        #region Details
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
                return NotFound();

            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
                return NotFound();

            return View(role);
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(string id)
        {
            if (id == null)
                return NotFound();

            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
                return NotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, IdentityRole identityRole)
        {
            if (id != identityRole.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(id);
                role.Name = identityRole.Name;
                role.NormalizedName = role.Name.ToUpper();

                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }
            return View(identityRole);

        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
                return NotFound();

            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
                return NotFound();

            var result=await roleManager.DeleteAsync(role);

            if(result.Succeeded)
                return RedirectToAction("Index");

            foreach (var error in result.Errors)
                ModelState.AddModelError("", error.Description);

            return RedirectToAction("Index");
        }
        #endregion

        #region AddOrRemoveUsers
        public async Task<IActionResult> AddOrRemoveUsers(string RoleId)
        {
            var role = await roleManager.FindByIdAsync(RoleId);
            if(role is null)
                return NotFound();

            ViewBag.RoleId = RoleId;
            var users = new List<UserInRoleViewModel>();
            foreach (var user in userManager.Users)
            {
                var userInRole = new UserInRoleViewModel()
                {
                    UserId=user.Id,
                    UserEmail=user.Email,
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                    userInRole.IsSelected = true;
                else
                    userInRole.IsSelected = false;

                users.Add(userInRole);

            }
            return View(users);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleViewModel> models,string RoleId)
        {
            var role = await roleManager.FindByIdAsync(RoleId);

            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var item in models)
                {
                    var user = await userManager.FindByIdAsync(item.UserId);
                    if (user is not null)
                    {
                        if (item.IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                            await userManager.AddToRoleAsync(user, role.Name);
                        else if (!item.IsSelected && (await userManager.IsInRoleAsync(user, role.Name)))
                            await userManager.RemoveFromRoleAsync(user, role.Name);

                    }

                }
                return RedirectToAction("Update", new { id = RoleId });
            }
            return View(models);
        }
        #endregion
    }
}

PL/Controllers/UsersController.cs
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
    
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public UsersController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

        #region Index
        public async Task<IActionResult> Index(string searchValue = "")
        {
            if (string.IsNullOrEmpty(searchValue))
            {
                var users = userManager.Users;
                return View(users);
            }
            else
            {
                var user = await userManager.FindByEmailAsync(searchValue.Trim());
                var userInList = new List<ApplicationUser>() { user };

                return View(userInList);
            }
        }
        #endregion

        #region Details
        public async Task<IActionResult> Details(string id)
        {
            if (id is null)
                return NotFound();

            var user = await userManager.FindByIdAsync(id);
            if (user is null)
                return NotFound();

            return View(user);
        }
        #endregion


        #region Update
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(string id)
        {
            if (id is null)
                return NotFound();
            var user = await userManager.FindByIdAsync(id);
            if (user is null)
                return NotFound();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, ApplicationUser applicationUser)
        {
            if(id!= applicationUser.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                var user= await userManager.FindByIdAsync(id);
                user.UserName= applicationUser.UserName;
                user.PhoneNumber= applicationUser.PhoneNumber;
                user.NormalizedUserName = applicationUser.UserName.ToUpper();

                var result=await userManager.UpdateAsync(user);
                if(result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }
            return View(applicationUser);
        }


        #endregion

        #region Delete
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id is null)
                return NotFound();
            var user = await userManager.FindByIdAsync(id);
            if (user is null)
                return NotFound();

            var result = await userManager.DeleteAsync(user);
            if (result.Succeeded)
                return RedirectToAction("Index");

            foreach (var error in result.Errors)
                ModelState.AddModelError("", error.Description);

            return RedirectToAction("Index");

        }
        #endregion
    }
}

PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>

    <!-- Custom Theme files -->
    <link rel="stylesheet" href="~/css/StyleSheet.css" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- Web Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- //Web Font -->

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    @* Additional scripts can be added using @RenderSection("Scripts", required: false) *@
    @RenderSection("Scripts", required: false)
</head>

<body>
    <!-- Main Content -->
    <div class="main-w3layouts wrapper">
        <h1>@ViewData["Title"]</h1>
        @RenderBody()

        <!-- Copyright -->
        <div class="colorlibcopy-agile">
            <p>© 2023 Professional Signup Form. All rights reserved | Design by <a href="#">MostafaBdr</a></p>
        </div>
        <!-- //Copyright -->
        <!-- Bubbles Animation -->
        <ul class="colorlib-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
        <!-- //Bubbles Animation -->
    </div>
    <!-- //Main Content -->
</body>

</html>

PL/Views/Shared/_ButtonsPartialView.cshtml
@model string

<div class="btn-group" role="group">
   <td>
        <a class="btn btn-success" asp-action="Details" asp-route-id="@Model" data-toggle="tooltip" title="Details">
            <i class="fas fa-eye"></i> Details
        </a>
   </td>
    <td>
        <a class="btn btn-warning" asp-action="Update" asp-route-id="@Model" data-toggle="tooltip" title="Update">
            <i class="fas fa-edit"></i> Update
        </a>
    </td>
   <td>
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model" data-toggle="tooltip" title="Delete">
            <i class="fas fa-trash"></i> Delete
        </a>
   </td>
</div>

PL/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        @* @if(signInManager.IsSignedIn(User)&& User.IsInRole("Admin"))
                        { *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                       @*  }
                        else if (signInManager.IsSignedIn(User) && User.IsInRole("HR"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        } *@
                    </ul>
                    <!-- Sign Out button styled as a button with red border, white text, and hover effect -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="btn btn-outline-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>